import type {Metadata} from "next";
import "./globals.css";
import Header from "@/src/components/header/Header";
import Footer from "@/src/components/footer/Footer";


export const metadata: Metadata = {
  title: " Movie site App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode }>) {

  return (
    <html lang="en" className="dark">
      <body className="min-h-full flex flex-col">
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
